backend:
  name: github
  repo: Ibnuwu/airsenuwu
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", required: false}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown", required: false}

  - name: "blog"
    label: "Cerpen / Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "creative"
    label: "Creative Work"
    folder: "content/creative"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Category", name: "category", widget: "select", options: ["photography", "artwork", "design", "experiment"]}
      - {label: "Description", name: "description", widget: "string", required: false}